@host=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwic3ViIjo5LCJpYXQiOjE3MDQxNzMyMTh9.Oh8aK8DUeSHkzzpj9li0B4f5KBqvGRf1M5eLYiuClSA
### 회원가입
POST {{host}}/user/register
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "1234",
    "nickname": "어드민"
}

### 로그인
POST {{host}}/user/login
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "1234"
}

### 내 정보 조회
GET {{host}}/user/myProfile
Content-Type: application/json
Authorization: Bearer {{token}}
