@host=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwic3ViIjo5LCJpYXQiOjE3MDQxNzMyMTh9.Oh8aK8DUeSHkzzpj9li0B4f5KBqvGRf1M5eLYiuClSA
### 공연 생성
POST {{host}}/performance
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "발탄 레이드의 등장",
    "content": "낙사 지옥의 마수군단장의 등장",
    "date": ["2023-09-13", "10:00"],
    "venue": "아크라시아",
    "seatInfo": "G열10",
    "image": "이미지 준비중",
    "category": "게임",
    "price": 50000
}

### 공연 전체 목록 조회
GET {{host}}/performance
Content-Type: application/json
Authorization: Bearer {{token}}

### 공연명 목록 조회
GET {{host}}/performance/search?title=카멘
Content-Type: application/json
Authorization: Bearer {{token}}